### ISSUE TITLE
Unresponsive alarm buttons due to inconsistent capitalization / small errors

### ISSUE THREAD

**Issue by DrunkOnHotCoco** [poe-iit/POE-AIO#2]
I'm just going to put the errors I found in the codebase that I believe are causing the unresponsive buttons for the Shooter and Public Safety buttons so we can fix them easily during the next meeting.

Firstly, [this switch statement in client2.go](https://github.com/poe-iit/POE-AIO/blob/f363080fcd896282e66c7ba9bd59aa2a852f593e/client2.go#L143) (the touchscreen client) is checking for inconsistently capitalized case strings. This is an issue since all the POST requests produced by [the server's Javascript](https://github.com/poe-iit/POE-AIO/blob/f363080fcd896282e66c7ba9bd59aa2a852f593e/website/site.js#L28-L43) uses only non-capitalized case strings. 

Next, [the function writeToGPIO()](https://github.com/poe-iit/POE-AIO/blob/f363080fcd896282e66c7ba9bd59aa2a852f593e/client2.go#L72) in the same file is missing a "Safety" case.

Thirdly, the [Environmental Out GPIO ](https://github.com/poe-iit/POE-AIO/blob/f363080fcd896282e66c7ba9bd59aa2a852f593e/client2.go#L61)pin is never set to High unlike the other pins, and is instead only set as an output pin. 

The last thing isn't a huge issue but environmental is spelled wrong throughout the code-base, so we might want to fix that to make sure no future problems occur because of it.

**Comment by trafis** [comment]
I went ahead and fixed some of the small-capitalization bugs and the critical webserver path error.  We never found an audio file for the safety case which is why I left it out for ipro day. The environmental out gpio was giving us some weird behavior because of the relay which is why it was only set to high. It did function during ipro day, but further debugging is certainly required.

**Comment by DrunkOnHotCoco** [comment]
Awesome, I really appreciate your help!
